test: &default

  # Credentials for REST APIs
  client_id: AW4rLHkwrfrPY3l4PiSZnwFw0HBGwe16YYkyjjqj1RTkau3l9TutmbPCFEaLab75YD6DHg2kUrNZ2h02
  client_secret: EExheOcDcBYpg8pSb8rm9PIaK6H_pHNk5A6QjaLRpVYZKyP1hhSpnPkzDOaFDaD3akXW4uvyfGJZL__z

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: railsprueba@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
   <<: *default
  # client_id: AW4rLHkwrfrPY3l4PiSZnwFw0HBGwe16YYkyjjqj1RTkau3l9TutmbPCFEaLab75YD6DHg2kUrNZ2h02
  # client_secret: EExheOcDcBYpg8pSb8rm9PIaK6H_pHNk5A6QjaLRpVYZKyP1hhSpnPkzDOaFDaD3akXW4uvyfGJZL__z

  # # Mode can be 'live' or 'sandbox'
  # mode: sandbox

  # # Credentials for Classic APIs
  # app_id: APP-80W284485P519543T
  # username: jb-us-seller_api1.paypal.com
  # password: WX4WTU3S8MY44S7F
  # signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # # With Certificate
  # # cert_path: "config/cert_key.pem"
  # sandbox_email_address: railsprueba@gmail.com

production:
  <<: *default
  mode: live
